apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: web
  namespace: default
  annotations:
    managed-by: Helm
binaryData: {}
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        root /usr/share/nginx/html;
        location / {
          index index.html;
        }
        location /data.json {
          alias /usr/share/nginx/html/data.json;
          add_header Content-Type application/json;
        }
      }
    }
