apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          env:
            - name: KAFKA_CFG_KRAFT_MODE
              value: "true"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CFG_NODE_ID
              value: "1"
            - name: KAFKA_KRAFT_CLUSTER_ID
              value: "yUp2jW5NRoWxExU7vOAZfQ"
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:9092"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "1@localhost:9093"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
          ports:
            - containerPort: 9092
            - containerPort: 9093
          #lifecycle:
          #  postStart:
          #    exec:
          #      command:
          #        - /bin/bash
          #        - -c
          #        - |
          #          for i in {1..5}; do
          #            kafka-topics.sh --bootstrap-server localhost:9092 --create --if-not-exists --topic earthquakes --partitions 1 --replication-factor 1 && break
          #            echo "Retrying... $i"
          #            sleep 5
          #          done
          #          for i in {1..5}; do
          #            kafka-topics.sh --bootstrap-server localhost:9092 --create --if-not-exists --topic quake-alerts --partitions 1 --replication-factor 1 && break
          #            echo "Retrying... $i"
          #            sleep 5
          #          done
