apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: docker.io/bitnami/kafka@sha256:5ecb43a7a8b5a155f7b6c6d1f3e9cf173b89e457d171a618a7e093032d1c8f1d
          env:
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:9092"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "broker"
            - name: KAFKA_CFG_BROKER_ID
              value: "0"
            - name: BITNAMI_DEBUG
              value: "true"
            - name: KAFKA_CFG_NODE_ID
              value: "0"
          ports:
            - containerPort: 9092
