apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing
  template:
    metadata:
      labels:
        app: landing
    spec:
      containers:
        - name: landing
          image: "{{ .Values.ecr_repository }}/{{ .Values.landing.name }}:{{ .Values.landing.tag }}"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: landing
spec:
  type: NodePort
  selector:
    app: landing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
