apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: "{{ .Values.ecr_repository }}/{{ .Values.producer.name }}:{{ .Values.producer.tag }}"
          imagePullPolicy: {{ .Values.producer.pullPolicy }}



