apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
        - name: data-volume
          emptyDir: { }
        #- name: nginx-config
        #  configMap:
        #    name: nginx-config
      containers:
        - name: web
          image: "{{ .Values.ecr_repository }}/{{ .Values.web.name }}:{{ .Values.web.tag }}"
          imagePullPolicy: {{ .Values.web.pullPolicy }}
          env:
            - name: DB_HOST
              value: earthquake-postgres-postgresql.default.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: postgres
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: earthquake-postgres-postgresql
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
