apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-main
  template:
    metadata:
      labels:
        app: web-main
    spec:
      containers:
        - name: web-main
          image: "{{ .Values.ecr_repository }}/{{ .Values.webmain.name }}:{{ .Values.webmain.tag }}"
          imagePullPolicy: {{ .Values.webmain.pullPolicy }}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-main
spec:
  type: NodePort
  selector:
    app: web-main
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
