apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-earthquakes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-earthquakes
  template:
    metadata:
      labels:
        app: web-earthquakes
    spec:
      volumes:
        - name: data-volume
          emptyDir: { }
        #- name: nginx-config
        #  configMap:
        #    name: nginx-config
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: web-earthquakes
          image: "{{ .Values.ecr_repository }}/{{ .Values.webearthquakes.name }}:{{ .Values.webearthquakes.tag }}"
          imagePullPolicy: {{ .Values.webearthquakes.pullPolicy }}
          ports:
            - containerPort: 80 #add
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: quakes
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: earthquake-postgres-postgresql
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: web-earthquakes
spec:
  type: NodePort
  selector:
    app: web-earthquakes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 #add

#apiVersion: v1
#kind: Service
#metadata:
#  name: web
#spec:
#  selector:
#    app: web
#  ports:
#    - port: 80
#      targetPort: 80
#      nodePort: 30080
#  type: NodePort
#


