apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment
  template:
    metadata:
      labels:
        app: sentiment
    spec:
      containers:
        - name: sentiment
          image: "{{ .Values.image.repository }}-sentiment:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}