kafkaImage: bitnami/kafka:latest
producerImage: earthquake-producer:latest
consumerImage: localhost:5000/earthquake-consumer:latest
webImage: localhost:5000/earthquake-web:latest


ecr_repository: 032021926264.dkr.ecr.us-east-1.amazonaws.com

producer:
  name: producer
  tag: latest
  pullPolicy: Always

consumer:
  name: consumer
  tag: latest
  pullPolicy: Always

web:
  name: web
  tag: latest
  pullPolicy: Always

quakedetectorsvc:
  name: quakedetectorsvc
  tag: latest
  pullPolicy: Always

alertdispatchersvc:
  name: alertdispatchersvc
  tag: latest
  pullPolicy: Always

