apiVersion: v1
kind: Pod
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  containers:
    - name: zookeeper
      image: bitnami/zookeeper:latest
      env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
      ports:
        - containerPort: 2181


