name: Build and Deploy

on:
  push:
    branches:
      - aws

jobs:
########################################################
#   
#   ██████╗ ██╗   ██╗██╗██╗     ██████╗ 
#   ██╔══██╗██║   ██║██║██║     ██╔══██╗
#   ██████╔╝██║   ██║██║██║     ██║  ██║
#   ██╔══██╗██║   ██║██║██║     ██║  ██║
#   ██████╔╝╚██████╔╝██║███████╗██████╔╝
#   ╚═════╝  ╚═════╝ ╚═╝╚══════╝╚═════╝ 
# 
########################################################

  #debug-commit-info:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Show changed files
  #      run: |
  #        echo "Modified:"
  #        echo "${{ toJson(github.event.head_commit.modified) }}"
  #        echo "Added:"
  #        echo "${{ toJson(github.event.head_commit.added) }}"
  #        echo "Removed:"
  #        echo "${{ toJson(github.event.head_commit.removed) }}"

  #############
  # WEB
  #############
  build-web-main:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::032021926264:role/github-oidc-provider-aws
          aws-region: us-east-1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and Push [main] image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: main
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker buildx build --platform linux/arm64 --tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --push ./Application/web/$ECR_REPOSITORY

  build-web-earthquakes:
    #if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.modified, '\n'), 'Application/web/earthquakes/') }}
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::032021926264:role/github-oidc-provider-aws
          aws-region: us-east-1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and Push [earthquakes] image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: earthquakes
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker buildx build --platform linux/arm64 --tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --push ./Application/web/$ECR_REPOSITORY




########################################################
#   
#   ██████╗ ███████╗██████╗ ██╗      ██████╗ ██╗   ██╗
#   ██╔══██╗██╔════╝██╔══██╗██║     ██╔═══██╗╚██╗ ██╔╝
#   ██║  ██║█████╗  ██████╔╝██║     ██║   ██║ ╚████╔╝ 
#   ██║  ██║██╔══╝  ██╔═══╝ ██║     ██║   ██║  ╚██╔╝  
#   ██████╔╝███████╗██║     ███████╗╚██████╔╝   ██║   
#   ╚═════╝ ╚══════╝╚═╝     ╚══════╝ ╚═════╝    ╚═╝   
#                    
########################################################
  deploy:
    needs:
      - build-web-main
      - build-web-earthquakes
    #if: ${{ always() && (needs.build-web-main.result == 'success' || needs.build-web-earthquakes.result == 'success' ) }}
    runs-on: [self-hosted, Linux, ARM64, k3s]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      - name: Deploy Helm Chart
      
        run: |
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
          #helm template ./Helm/charts/earthquake-monitor --debug
          helm upgrade --install earthquake-monitor ./Helm/charts/earthquake-monitor \
            --namespace default \
            --set producer.image.repository=032021926264.dkr.ecr.us-east-1.amazonaws.com/producer --set producer.image.tag=${{ github.sha }} \
            --set consumer.image.repository=032021926264.dkr.ecr.us-east-1.amazonaws.com/consumer --set consumer.image.tag=${{ github.sha }} \
            --set quake-detector-svc.image.repository=032021926264.dkr.ecr.us-east-1.amazonaws.com/quake-detector-svc --set quakedetectorsvc.tag=${{ github.sha }} \
            --set alert-dispatcher-svc.image.repository=032021926264.dkr.ecr.us-east-1.amazonaws.com/alert-dispatcher-svc --set alertdispatchersvc.tag=${{ github.sha }} \
            --set web-main.image.repository=032021926264.dkr.ecr.us-east-1.amazonaws.com/web-main --set webmain.tag=${{ github.sha }} \
            --set web-earthquakes.image.repository=032021926264.dkr.ecr.us-east-1.amazonaws.com/web-earthquakes --set webearthquakes.tag=${{ github.sha }} \
            --timeout 3m
          #kubectl rollout restart deployment landing


