name: Build and Deploy

on:
  push:
    branches:
      - aws

# Shared environment values
env:
  AWS_REGION: us-east-1
  ROLE_TO_ASSUME: arn:aws:iam::032021926264:role/github-actions-ecr

jobs:
###############################################################################
# Build jobs – identical pattern, just the directory + repo name changes
###############################################################################
  build-consumer:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Dump GitHub OIDC claims
        id: show-claims
        uses: actions/github-script@v6
        with:
          script: |
            const jwt = require('jsonwebtoken');
            const token = await core.getIDToken('sts.amazonaws.com');   // same audience you pass below
            const claims = jwt.decode(token, { complete: false });
            console.log('--- OIDC token claims ---');
            console.log(JSON.stringify(claims, null, 2));

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com          # <- pin the aud claim

      - uses: docker/setup-buildx-action@v3

      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Build & push consumer image
        run: |
          docker buildx build --platform linux/arm64 \
            --tag ${{ steps.login-ecr.outputs.registry }}/consumer:latest \
            --push ./Application/consumer

  build-producer:
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read }
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com
      - uses: docker/setup-buildx-action@v3
      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
      - name: Build & push producer image
        run: |
          docker buildx build --platform linux/arm64 \
            --tag ${{ steps.login-ecr.outputs.registry }}/producer:latest \
            --push ./Application/producer

  build-alert-dispatcher-svc:
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read }
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com
      - uses: docker/setup-buildx-action@v3
      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
      - name: Build & push alert‑dispatcher‑svc image
        run: |
          docker buildx build --platform linux/arm64 \
            --tag ${{ steps.login-ecr.outputs.registry }}/alert-dispatcher-svc:latest \
            --push ./Application/alert-dispatcher-svc

  build-quake-detector-svc:
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read }
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com
      - uses: docker/setup-buildx-action@v3
      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
      - name: Build & push quake‑detector‑svc image
        run: |
          docker buildx build --platform linux/arm64 \
            --tag ${{ steps.login-ecr.outputs.registry }}/quake-detector-svc:latest \
            --push ./Application/quake-detector-svc

  build-web-main:
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read }
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com
      - uses: docker/setup-buildx-action@v3
      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
      - name: Build & push web‑main image
        run: |
          docker buildx build --platform linux/arm64 \
            --tag ${{ steps.login-ecr.outputs.registry }}/web-main:latest \
            --push ./Application/web/main

  build-web-earthquakes:
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read }
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com
      - uses: docker/setup-buildx-action@v3
      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
      - name: Build & push web‑earthquakes image
        run: |
          docker buildx build --platform linux/arm64 \
            --tag ${{ steps.login-ecr.outputs.registry }}/web-earthquakes:latest \
            --push ./Application/web/earthquakes

###############################################################################
# Deploy step (unchanged except for indent fix)
###############################################################################
  deploy:
    needs:
      - build-web-main
      - build-web-earthquakes
      - build-consumer
      - build-producer
      - build-quake-detector-svc
      - build-alert-dispatcher-svc
    runs-on: [self-hosted, Linux, ARM64, k3s]
    steps:
      - uses: actions/checkout@v3

      - uses: azure/setup-helm@v3
      - uses: azure/setup-kubectl@v3

      - name: Deploy Helm chart
        run: |
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
          helm upgrade --install earthquake-monitor ./Helm/charts/earthquake-monitor \
            --namespace default \
            --set producer.image.repository=032021926264.dkr.ecr.us-east-1.amazonaws.com/producer --set producer.image.tag=latest \
            --set consumer.image.repository=032021926264.dkr.ecr.us-east-1.amazonaws.com/consumer --set consumer.image.tag=latest \
            --set quake-detector-svc.image.repository=032021926264.dkr.ecr.us-east-1.amazonaws.com/quake-detector-svc --set quakedetectorsvc.tag=latest \
            --set alert-dispatcher-svc.image.repository=032021926264.dkr.ecr.us-east-1.amazonaws.com/alert-dispatcher-svc --set alertdispatchersvc.tag=latest \
            --set web-main.image.repository=032021926264.dkr.ecr.us-east-1.amazonaws.com/web-main --set webmain.tag=latest \
            --set web-earthquakes.image.repository=032021926264.dkr.ecr.us-east-1.amazonaws.com/web-earthquakes --set webearthquakes.tag=latest \
            --timeout 3m
