name: Earthquake Deploy

on:
  #push:
  #  branches:
  #    - awsv2
  #  paths:
  #    - 'Application/web/main/**'
  workflow_dispatch:  # Enables manual "Run workflow" button in GitHub UI

# Shared environment values
env:
  AWS_REGION: us-east-1
  ROLE_TO_ASSUME: arn:aws:iam::032021926264:role/github_actions

jobs:

########################################################
#   
#   ██████╗ ███████╗██████╗ ██╗      ██████╗ ██╗   ██╗
#   ██╔══██╗██╔════╝██╔══██╗██║     ██╔═══██╗╚██╗ ██╔╝
#   ██║  ██║█████╗  ██████╔╝██║     ██║   ██║ ╚████╔╝ 
#   ██║  ██║██╔══╝  ██╔═══╝ ██║     ██║   ██║  ╚██╔╝  
#   ██████╔╝███████╗██║     ███████╗╚██████╔╝   ██║   
#   ╚═════╝ ╚══════╝╚═╝     ╚══════╝ ╚═════╝    ╚═╝   
#                    
########################################################
  deploy:
    #needs:
    #  - build-web-earthquakes
    #  - build-consumer
    #  - build-producer
    #  - build-quake-detector-svc
    #  - build-alert-dispatcher-svc
    runs-on: [self-hosted, Linux, ARM64, k3s]
    steps:
      - uses: actions/checkout@v3

      - uses: azure/setup-helm@v3
      - uses: azure/setup-kubectl@v3

      - name: Deploy Helm chart
        run: |
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
          helm upgrade --install earthquake-monitor ./Helm/charts/earthquake-monitor \
            --namespace default \
            --set producer.image.repository=032021926264.dkr.ecr.us-east-1.amazonaws.com/producer --set producer.image.tag=latest \
            --set consumer.image.repository=032021926264.dkr.ecr.us-east-1.amazonaws.com/consumer --set consumer.image.tag=latest \
            --set quake-detector-svc.image.repository=032021926264.dkr.ecr.us-east-1.amazonaws.com/quake-detector-svc --set quakedetectorsvc.tag=latest \
            --set alert-dispatcher-svc.image.repository=032021926264.dkr.ecr.us-east-1.amazonaws.com/alert-dispatcher-svc --set alertdispatchersvc.tag=latest \
            --set web-earthquakes.image.repository=032021926264.dkr.ecr.us-east-1.amazonaws.com/web-earthquakes --set webearthquakes.tag=latest \
            --timeout 3m
