name: Sedaro Build ALL

on:
  #push:
  #  branches:
  #    - awsv2
  #  paths:
  #    - 'Application/web/main/**'
  workflow_dispatch:  # Enables manual "Run workflow" button in GitHub UI

# Shared environment values
env:
  AWS_REGION: us-east-1
  ROLE_TO_ASSUME: arn:aws:iam::032021926264:role/github_actions
  ECR_REPO: 032021926264.dkr.ecr.us-east-1.amazonaws.com
  #IMAGE_TAG: ${{ github.sha }}
  IMAGE_TAG: latest

jobs:
########################################################
#   
#   ██████╗ ██╗   ██╗██╗██╗     ██████╗ 
#   ██╔══██╗██║   ██║██║██║     ██╔══██╗
#   ██████╔╝██║   ██║██║██║     ██║  ██║
#   ██╔══██╗██║   ██║██║██║     ██║  ██║
#   ██████╔╝╚██████╔╝██║███████╗██████╔╝
#   ╚═════╝  ╚═════╝ ╚═╝╚══════╝╚═════╝ 
# 
########################################################

  build-web:
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read }
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com
      - uses: docker/setup-buildx-action@v3
      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
      - name: Build/Push [web] image
        run: |
          docker build -t $ECR_REPO/sedaro-web:$IMAGE_TAG ./Application/sedaro-nano/web
          docker push $ECR_REPO/sedaro-web:$IMAGE_TAG

  build-app:
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read }
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com
      - uses: docker/setup-buildx-action@v3
      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
      - name: Build/Push [app] image
        run: |
          docker build -t $ECR_REPO/sedaro-app:$IMAGE_TAG ./Application/sedaro-nano/app
          docker push $ECR_REPO/sedaro-app:$IMAGE_TAG
