name: Web Build and Deploy

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ROLE_TO_ASSUME: arn:aws:iam::032021926264:role/github_actions
  IMAGE_TAG: ${{ github.sha }}

jobs:
########################################################
#   
#   ██████╗ ██╗   ██╗██╗██╗     ██████╗ 
#   ██╔══██╗██║   ██║██║██║     ██╔══██╗
#   ██████╔╝██║   ██║██║██║     ██║  ██║
#   ██╔══██╗██║   ██║██║██║     ██║  ██║
#   ██████╔╝╚██████╔╝██║███████╗██████╔╝
#   ╚═════╝  ╚═════╝ ╚═╝╚══════╝╚═════╝ 
# 
########################################################
  build-web-main:
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read }
    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com

      - uses: docker/setup-buildx-action@v3

      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Build & push web‑main image (SHA and latest)
        run: |
          export DOCKER_BUILDKIT=0
          docker build -t ${{ steps.login-ecr.outputs.registry }}/web-main:${{ env.IMAGE_TAG }} ./Application/web/main
          docker tag ${{ steps.login-ecr.outputs.registry }}/web-main:${{ env.IMAGE_TAG }} ${{ steps.login-ecr.outputs.registry }}/web-main:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/web-main:${{ env.IMAGE_TAG }}
          docker push ${{ steps.login-ecr.outputs.registry }}/web-main:latest

########################################################
#   
#   ██████╗ ███████╗██████╗ ██╗      ██████╗ ██╗   ██╗
#   ██╔══██╗██╔════╝██╔══██╗██║     ██╔═══██╗╚██╗ ██╔╝
#   ██║  ██║█████╗  ██████╔╝██║     ██║   ██║ ╚████╔╝ 
#   ██║  ██║██╔══╝  ██╔═══╝ ██║     ██║   ██║  ╚██╔╝  
#   ██████╔╝███████╗██║     ███████╗╚██████╔╝   ██║   
#   ╚═════╝ ╚══════╝╚═╝     ╚══════╝ ╚═════╝    ╚═╝   
#                    
########################################################
  deploy:
    needs:
      - build-web-main
    runs-on: [self-hosted, daveops]
    steps:
      - uses: actions/checkout@v3

      - uses: azure/setup-helm@v3
      - uses: azure/setup-kubectl@v3

      - name: Deploy Helm chart
        run: |
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
          helm upgrade --install daveops ./Helm/charts/daveops \
            --namespace default \
            --set web-main.image.repository=032021926264.dkr.ecr.us-east-1.amazonaws.com/web-main \
            --set webmain.tag=${IMAGE_TAG} \
            --timeout 3m
